#### 1. Import the NUMPY package under the name np.



In [1]:
import numpy as np

#### 2. Print the NUMPY version and the configuration.



In [2]:
print(np.__version__)
print(np.__config__)

1.16.2
<module 'numpy.__config__' from '/Users/selimmellouk/.local/lib/python3.6/site-packages/numpy/__config__.py'>


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
#### Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Permet de faire des print plus jolis
from pprint import pprint

# Méthode 1 : Distribution uniforme entre 0 et 1
a_1 = np.random.rand(2,3,5)
print("dim 1 :",len(a_1))
print("dim 2 :",len(a_1[0]))
print("dim 3 :",len(a_1[0][0]))
print("First element :", ((a_1[0][0][0])))
# On affiche le tableau
pprint((a_1))


# Méthode 2 : On ne génère que des entiers (distributoion uniforme)
# On génère des entiers entre 0 et 5 (exclus), contenus dans une matrice de taille
# 2 * 3 * 5
a_2 = np.random.randint(5, size=(2,3,5))
print("dim 1 :",len(a_2))
print("dim 2 :",len(a_2[0]))
print("dim 3 :",len(a_2[0][0]))
print("First element :", ((a_2[0][0][0])))
# On affiche le tableau
pprint((a_2))


# Méthode 3 : Distribution uniforme entre 0 et 1
a_3 = np.random.random_sample(size=(2, 3, 5))
print("dim 1 :",len(a_3))
print("dim 2 :",len(a_3[0]))
print("dim 3 :",len(a_3[0][0]))
print("First element :", ((a_3[0][0][0])))
# On affiche le tableau
pprint(a_3)

dim 1 : 2
dim 2 : 3
dim 3 : 5
First element : 0.09258278563454969
array([[[0.09258279, 0.71673152, 0.16997761, 0.66387199, 0.43099545],
        [0.06651274, 0.92955937, 0.83758105, 0.37591409, 0.6623897 ],
        [0.83360669, 0.15003446, 0.83043076, 0.01201128, 0.39025089]],

       [[0.76748838, 0.21918491, 0.93374386, 0.859573  , 0.43534897],
        [0.79640628, 0.91358241, 0.63925974, 0.90784757, 0.95796414],
        [0.60231852, 0.17703479, 0.50917806, 0.31700782, 0.79614507]]])
dim 1 : 2
dim 2 : 3
dim 3 : 5
First element : 0
array([[[0, 0, 3, 4, 3],
        [2, 2, 2, 3, 0],
        [3, 4, 1, 1, 2]],

       [[3, 2, 1, 4, 0],
        [0, 0, 3, 2, 2],
        [0, 3, 4, 1, 4]]])
dim 1 : 2
dim 2 : 3
dim 3 : 5
First element : 0.7759947520071501
array([[[0.77599475, 0.66119779, 0.90318828, 0.93591888, 0.43796036],
        [0.15679764, 0.49979713, 0.94860446, 0.23972249, 0.86777747],
        [0.53055437, 0.30131791, 0.55619985, 0.94034123, 0.94171891]],

       [[0.59777451, 0.96077901

#### 4. Print a.

In [4]:
print(a_1)
print(a_2)
print(a_3)

[[[0.09258279 0.71673152 0.16997761 0.66387199 0.43099545]
  [0.06651274 0.92955937 0.83758105 0.37591409 0.6623897 ]
  [0.83360669 0.15003446 0.83043076 0.01201128 0.39025089]]

 [[0.76748838 0.21918491 0.93374386 0.859573   0.43534897]
  [0.79640628 0.91358241 0.63925974 0.90784757 0.95796414]
  [0.60231852 0.17703479 0.50917806 0.31700782 0.79614507]]]
[[[0 0 3 4 3]
  [2 2 2 3 0]
  [3 4 1 1 2]]

 [[3 2 1 4 0]
  [0 0 3 2 2]
  [0 3 4 1 4]]]
[[[0.77599475 0.66119779 0.90318828 0.93591888 0.43796036]
  [0.15679764 0.49979713 0.94860446 0.23972249 0.86777747]
  [0.53055437 0.30131791 0.55619985 0.94034123 0.94171891]]

 [[0.59777451 0.96077901 0.76088055 0.99972751 0.05927621]
  [0.91022093 0.91077384 0.80356764 0.11992734 0.0577722 ]
  [0.12594256 0.42067702 0.0359007  0.82451708 0.05132666]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#### Assign the array to variable "b"

In [5]:
# On reprend le format précisé en 4. pour a
a = np.random.rand(2,3,5)

b = np.ones((5, 2, 3))

#### 6. Print b.



In [6]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do a and b have the same size? How do you prove that in Python code?

In [7]:
# No they do not : 
# a : dim 1 = 2, dim 2 = 3, dim 3 = 5 
# b : dim 1 = 5, dim 2 = 2, dim 3 = 3
print("shape of a : {}".format(a.shape))
print("shape of b : {}".format(b.shape))
print(b.shape == a.shape)

shape of a : (2, 3, 5)
shape of b : (5, 2, 3)
False


#### 8. Are you able to add a and b? Why or why not?



In [8]:
#print(a + b)
print("We get an error because the shapes are not the same")
print("shape of a : {}".format(a.shape))
print("shape of b : {}".format(b.shape))

We get an error because the shapes are not the same
shape of a : (2, 3, 5)
shape of b : (5, 2, 3)


#### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [9]:
print("shape of b : {}".format(b.shape))
# b has format (5, 2, 3) and a has format (2, 3, 5)
# so we need to swap dim 0 and dim 1 in b, then we get (2, 5, 3)
c = np.swapaxes(b, 0, 1).copy()
print("With swap 1st step : shape of c : {}".format(c.shape))
# then we need to swap dim 1 and dim 2 in the c newly obtained and we get (2, 3, 5)
c = np.swapaxes(c, 1, 2)
print("With swap 2nd step : shape of c : {}".format(c.shape))
# Plus efficace : en 1 appel d'une fonction (merci Lauma)
c = b.transpose([1,2,0])
print("With transpose in 1 step : shape of c : {}".format(c.shape))



shape of b : (5, 2, 3)
With swap 1st step : shape of c : (2, 5, 3)
With swap 2nd step : shape of c : (2, 3, 5)
With transpose in 1 step : shape of c : (2, 3, 5)


#### 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [10]:
# We can then add
d = a + c
print("shape of a : {}".format(a.shape))
print("shape of c : {}".format(c.shape))
print("shape of d : {}".format(d.shape))
print(d)

shape of a : (2, 3, 5)
shape of c : (2, 3, 5)
shape of d : (2, 3, 5)
[[[1.57077857 1.96288253 1.61992657 1.52100226 1.35967137]
  [1.13454283 1.35628951 1.67825481 1.23878464 1.93798881]
  [1.07845615 1.61491044 1.85615836 1.13026705 1.75996258]]

 [[1.72905374 1.20623215 1.9215284  1.6003363  1.32077919]
  [1.50125649 1.16128121 1.75155692 1.45862719 1.28608066]
  [1.3164173  1.21154789 1.72827245 1.12609473 1.84026365]]]


#### 12. Multiply a and c. Assign the result to e.



In [11]:
e = a*c
print("shape of e : {}".format(e.shape))

shape of e : (2, 3, 5)


#### 13. Does e equal to a? Why or why not?

In [12]:
# Classical multiplication (with *) applied to 2 numpy darrays return 
# a vector of same shape than both a and c
# this is pairwise multiplication meaning : e[i][j][k] = a[i][j][k] * c[i][j][k]
# e = a because all elements of b are equal to 1
print(e == a)
print(e)
print(a)

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]
[[[0.57077857 0.96288253 0.61992657 0.52100226 0.35967137]
  [0.13454283 0.35628951 0.67825481 0.23878464 0.93798881]
  [0.07845615 0.61491044 0.85615836 0.13026705 0.75996258]]

 [[0.72905374 0.20623215 0.9215284  0.6003363  0.32077919]
  [0.50125649 0.16128121 0.75155692 0.45862719 0.28608066]
  [0.3164173  0.21154789 0.72827245 0.12609473 0.84026365]]]
[[[0.57077857 0.96288253 0.61992657 0.52100226 0.35967137]
  [0.13454283 0.35628951 0.67825481 0.23878464 0.93798881]
  [0.07845615 0.61491044 0.85615836 0.13026705 0.75996258]]

 [[0.72905374 0.20623215 0.9215284  0.6003363  0.32077919]
  [0.50125649 0.16128121 0.75155692 0.45862719 0.28608066]
  [0.3164173  0.21154789 0.72827245 0.12609473 0.84026365]]]


#### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [13]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print("max : {0:.2f}, min : {1:.2f}, mean : {2:.2f}".format(d_max, d_min, d_mean))
# Meaning : 0th value with 2 decimals, then 1st then 2nd  
# (from the 0th, 1st and 2nd value specified as an argument)

max : 1.96, min : 1.08, mean : 1.50


#### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [14]:
f = np.empty([2, 3, 5])
print(f.shape == d.shape)

True


#### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
#### If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
#### If a value equals to d_mean, assign 50 to the corresponding value in f.
#### Assign 0 to the corresponding value(s) in f for d_min in d.
#### Assign 100 to the corresponding value(s) in f for d_max in d.
#### In the end, f should have only the following values: 0, 25, 50, 75, and 100.
#### Note: you don't have to use Numpy in this question.

In [15]:
print("We first iterate over the first dimension which is equal to {}".format(len(d)))
print("We first iterate over the second dimension which is equal to {}".format(len(d[0])))
print("We first iterate over the second dimension which is equal to {}".format(len(d[0][0])))

# First dim = 2
for i in range(len(f)):
    # Second dim = 3
    for j in range(len(f[0])):
        # Third dim = 5
        for k in range(len(f[0][0])):
            if  d_min < d[i][j][k] < d_mean:
                f[i][j][k] = 25
            elif  d_mean < d[i][j][k] < d_max :
                f[i][j][k] = 75
            else:
                f[i][j][k] = 50
print(f)

We first iterate over the first dimension which is equal to 2
We first iterate over the second dimension which is equal to 3
We first iterate over the second dimension which is equal to 5
[[[75. 50. 75. 75. 25.]
  [25. 25. 75. 25. 75.]
  [50. 75. 75. 25. 75.]]

 [[75. 25. 75. 75. 25.]
  [75. 25. 75. 25. 25.]
  [25. 25. 75. 25. 75.]]]


#### 17. Print d and f. Do you have your expected f?

In [16]:
d = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print("max : {0:.2f}, min : {1:.2f}, mean : {2:.2f}".format(d_max, d_min, d_mean))
# Meaning : 0th value with 2 decimals, then 1st then 2nd  
# (from the 0th, 1st and 2nd value specified as an argument)

max : 1.97, min : 1.01, mean : 1.62


In [17]:
## Avec une boucle

print("We first iterate over the first dimension which is equal to {}".format(len(d)))
print("We first iterate over the second dimension which is equal to {}".format(len(d[0])))
print("We first iterate over the second dimension which is equal to {}".format(len(d[0][0])))

# First dim = 2
for i in range(len(d)):
    # Second dim = 3
    for j in range(len(d[0])):
        # Third dim = 5
        for k in range(len(d[0][0])):
            if  d_min < d[i][j][k] < d_mean:
                f[i][j][k] = 25
            elif  d_mean < d[i][j][k] < d_max :
                f[i][j][k] = 75
            elif d[i][j][k] == d_mean :
                f[i][j][k] = 50
            elif d[i][j][k] == d_min :
                f[i][j][k] = 0
            elif d[i][j][k] == d_max :
                f[i][j][k] = 100
              
            
# Beaucoup plus élégant : avec la fonction vectorize : 
# transforme une fonction qui prend en entrée un nombre, 
# en une fonction qui prend en entrée un vecteur et applique cette fonction a tous les éléments

# d will be an element of d
def f_fun(d_min, d_max, d_mean, d):
    if  d_min < d < d_mean:
        f = 25
    elif  d_mean < d < d_max :
        f = 75
    elif d == d_mean :
        f= 50
    elif d == d_min :
        f= 0
    elif d == d_max :
        f = 100
    return f

# python-function as ufunc
import numpy as np
vf= np.vectorize(lambda x :f_fun(d_min=d_min, d_max=d_max, d_mean=d_mean, d=x))
## On récupère bien le même output
f == vf(d)
print(vf(d))

We first iterate over the first dimension which is equal to 2
We first iterate over the second dimension which is equal to 3
We first iterate over the second dimension which is equal to 5
[[[ 75  75  75  25  75]
  [ 75  75  25  25  25]
  [ 75  25  75  75  75]]

 [[ 25  25  25  25 100]
  [ 75  75  75  75  75]
  [ 25  75   0  75  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
#### ("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:

In [19]:
   
# Beaucoup plus élégant : avec la fonction vectorize : 
# transforme une fonction qui prend en entrée un nombre, 
# en une fonction qui prend en entrée un vecteur et applique cette fonction a tous les éléments

# d will be an element of d
def f_fun(d_min, d_max, d_mean, d):
    if  d_min < d < d_mean:
        f = "B"
    elif  d_mean < d < d_max :
        f = "D"
    elif d == d_mean :
        f= "C"
    elif d == d_min :
        f= "A"
    elif d == d_max :
        f = "E"
    return f

# python-function as ufunc
import numpy as np
vf= np.vectorize(lambda x :f_fun(d_min=d_min, d_max=d_max, d_mean=d_mean, d=x))
print(vf(d))

[[['D' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'B']
  ['D' 'B' 'D' 'D' 'D']]

 [['B' 'B' 'B' 'B' 'E']
  ['D' 'D' 'D' 'D' 'D']
  ['B' 'D' 'A' 'D' 'D']]]


In [22]:
### Desired output
"""
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],
       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
""" 

"\narray([[[ 'D',  'D',  'D',  'B',  'D'],\n        [ 'D',  'D',  'B',  'B',  'B'],\n        [ 'D',  'B',  'D',  'D',  'D']],\n       [[ 'B',  'B',  'B',  'B',  'E'],\n        [ 'D',  'D',  'D',  'D',  'D'],\n        [ 'B',  'D',   'A',  'D', 'D']]])\n"